create database BT_Sql_Trigger;
use BT_Sql_Trigger;

CREATE TABLE KHACHHANG (
    MAKH INT PRIMARY KEY AUTO_INCREMENT,
    HOTEN VARCHAR(50),
    DCHI VARCHAR(50),
    SODT VARCHAR(15),
    NGSINH DATETIME,
    DOANHSO FLOAT,
    NGDK DATETIME
);

CREATE TABLE SANPHAM (
    MANV INT PRIMARY KEY AUTO_INCREMENT,
    HOTEN VARCHAR(50),
    NGVL DATETIME,
    SODT VARCHAR(15)
);

CREATE TABLE SANPHAM (
    MASP INT PRIMARY KEY AUTO_INCREMENT,
    TENSP VARCHAR(50),
    DVT VARCHAR(15),
    NUOCSX VARCHAR(30),
    GIA FLOAT
);

CREATE TABLE HOADON (
    SOHD INT PRIMARY KEY AUTO_INCREMENT,
    NGHD DATETIME,
    MAKH INT,
    MANV INT,
    TRIGIA FLOAT,
    FOREIGN KEY (MAKH)
        REFERENCES KHACHHANG (MAKH),
    FOREIGN KEY (MANV)
        REFERENCES SANPHAM (MANV)
);

CREATE TABLE CTHD (
    SOHD INT,
    MASP INT,
    SL INT,
    FOREIGN KEY (SOHD)
        REFERENCES HOADON (SOHD),
    FOREIGN KEY (MASP)
        REFERENCES SANPHAM (MASP),
    PRIMARY KEY (SOHD , MASP)
);
                        
-- câu 1:
SELECT count(distinCT CT.MASP) 
FROM HOADON HD JOIN CTHD CT ON HD.SOHD = CT.SOHD 
WHERE year(HD.nghd) = 2006  ;

-- câu 2:
SELECT max(HOADON.TRIGIA), min(HOADON.TRIGIA) 
FROM HOADON; 

-- câu 3:
SELECT avg(HOADON.TRIGIA) 
FROM HOADON
WHERE year(HOADON.NGHD) = 2006 ;

-- câu 4:
SELECT sum(HOADON.TRIGIA) 
FROM HOADON
WHERE year(HOADON.NGHD) = 2006 ;

-- câu 5:
SELECT max(HOADON.TRIGIA) 
FROM HOADON
WHERE year(NGHD) = 2006; 

-- câu 6:
SELECT KH.hoten, max(HD.TRIGIA)
FROM KHACHHANG KH JOIN HOADON HD ON KH.MAKH = hd.MAKH
WHERE year(NGHD) = 2006;

-- câu 7:
SELECT KH.MAKH,KH.hoten
FROM KHACHHANG kh
ORDER BY kh.doanhso desc
limit 3;

-- câu 8:
SELECT MASP, TENSP, GIA
FROM SANPHAM
WHERE GIA >= (
SELECT distinCT GIA FROM SANPHAM
ORDER BY GIA desc
limit 2,1
);

-- câu 9:
SELECT 
    MASP, TENSP, GIA
FROM
    SANPHAM
WHERE
    NUOCSX LIKE 'Thai Lan'
        AND GIA >= (SELECT DISTINCT
            GIA
        FROM
            SANPHAM
        ORDER BY GIA DESC
        LIMIT 2 , 1);
        
-- câu 10: 
SELECT MASP, TENSP, GIA
FROM SANPHAM
WHERE NUOCSX LIKE 'Trung Quoc' and GIA >= (
SELECT distinCT GIA FROM SANPHAM
ORDER BY GIA desc
limit 2,1
);

-- câu 11:
SELECT *, rank() over(ORDER BY doanhso DESC) as ranking FROM KHACHHANG;

-- câu 12:
SELECT count(MASP) 'Trung Quoc' 
FROM SANPHAM
WHERE NUOCSX LIKE 'Trung Quoc';

-- câu 13:
SELECT NUOCSX, count(MASP) 
FROM SANPHAM
GROUP BY NUOCSX;

-- câu 14:
SELECT NUOCSX , min(GIA) , max(GIA) , avg(GIA)  
FROM SANPHAM
GROUP BY NUOCSX;

-- câu 15:
SELECT NGHD , sum(TRIGIA)
FROM HOADON
GROUP BY NGHD
ORDER BY NGHD;

-- câu 16:
SELECT count(CTHD.sl) 
FROM CTHD JOIN HOADON ON HOADON.SOHD = CTHD.SOHD
WHERE mONth(NGHD) = 10 and year(NGHD) = 2006;

-- câu 17:
SELECT mONth(NGHD) , sum(TRIGIA) 
FROM HOADON
WHERE year(NGHD) = 2006
GROUP BY mONth(NGHD)
ORDER BY mONth(NGHD);

-- câu 18:
SELECT HOADON.SOHD , count(CTHD.MASP) 
FROM HOADON JOIN CTHD ON CTHD.SOHD = HOADON.SOHD
GROUP BY HOADON.SOHD
having count(CTHD.MASP) = 3 ;

-- câu 19:
SELECT HOADON.SOHD , count(CTHD.MASP) 
FROM HOADON JOIN CTHD ON CTHD.SOHD = HOADON.SOHD JOIN SANPHAM ON SANPHAM.MASP = CTHD.MASP
WHERE SANPHAM.NUOCSX = 'việt nam'
GROUP BY HOADON.SOHD
having count(CTHD.MASP) = 3 ;

-- câu 20:
SELECT KHACHHANG.MAKH, KHACHHANG.hoten,count(HOADON.SOHD)
FROM KHACHHANG JOIN HOADON ON HOADON.MAKH = KHACHHANG.MAKH
GROUP BY KHACHHANG.MAKH
having count(HOADON.SOHD) = (
SELECT count(SOHD)
FROM HOADON
GROUP BY MAKH
ORDER BY count(SOHD) desc
limit 1
);