CREATE DATABASE DVOTO;
use DVOTO;

CREATE TABLE NHACUNGCAP(
	MaNhaCC INT PRIMARY KEY,
    TenNhaCC VARCHAR(255),
    DiaChi VARCHAR(255),
    SoDT VARCHAR(255),
    MaSoThue VARCHAR(255)
);

CREATE TABLE DANGKYCUNGCAP(
	MaDKCC INT PRIMARY KEY,
    NgayBatDauCungCap DATE,
    NgayBatKetThucCap DATE,
    SOLuongXeDangKy INT,
    MaNhaCC INT,
    MaLoaiDV INT,
    Dongxe INT,
    MaMP INT,
    FOREIGN KEY (MaNhaCC) REFERENCES NHACUNGCAP(MaNhaCC),
    FOREIGN KEY (MaLoaiDV) REFERENCES LOAIDICHVU(MaLoaiDV),
    FOREIGN KEY (Dongxe) REFERENCES DONGXE(Dongxe),
    FOREIGN KEY (MaMP) REFERENCES MUCPHI(MaMP)
);

CREATE TABLE MUCPHI(
	MaMP INT PRIMARY KEY,
    DonGia DOUBLE,
    MoTa VARCHAR(1000)
);

CREATE TABLE LOAIDICHVU(
	MaLoaiDV INT PRIMARY KEY,
    TenLoaiDV VARCHAR(255)
);

CREATE TABLE DONGXE(
	DongXe INT PRIMARY KEY,
    HangXe VARCHAR(255),
    SoChoNgoi INT
);


INSERT INTO NHACUNGCAP
VALUES(101, 'Trung Quoc', 'Ha Noi', 034344352, 123),
		(201, 'Han Quoc', 'Sai gon', 044925922, 124),
        (301, 'Nhat Ban', 'Da Nang', 073569283, 125);
        
INSERT INTO MUCPHI
VALUES(345, 15000, 'Like new'),
		(456, 20000, 'New');

INSERT INTO LOAIDICHVU
VALUES (001, 'Sua chua'),
		(002, 'Bao tri');

INSERT INTO DONGXE
VALUES (770, 'KIA', 4),
        (660, 'Toyota', 4);

INSERT INTO DANGKYCUNGCAP
VALUES (777, '2015-11-20', '2020-11-20', 15, 101, 001, 550, 345);
		

-- cau3
SELECT SoChoNgoi
FROM DONGXE 
WHERE SoChoNgoi > 5;

-- cau4
SELECT *
FROM DANGKYCUNGCAP
JOIN (MUCPHI)
WHERE (DongXe = 'Toyota' AND DonGia = 15000) OR (DongXe = 'KIA' AND DonGia = 20000);

-- cau 5
SELECT NHACUNGCAP.TenNhaCC,  NHACUNGCAP.MaSoThue
FROM NHACUNGCAP
ORDER BY TenNhaCC ASC , MaSoThue DESC;

-- cau6
SELECT COUNT(MaDKCC) as SoLanDk
FROM DANGKYCUNGCAP
WHERE NgayBatDauCungCap = '2015-11-20';

-- cau7
SELECT dx1.HangXe
FROM DONGXE dx1	
WHERE dx1.DongXe = (SELECT max(dx2.DongXe) FROM DONGXE dx2 WHERE dx1.HangXe = dx2.HangXe);

-- cau8
SELECT DANGKYCUNGCAP.MaDKCC,NHACUNGCAP.*,LOAIDICHVU.TenLoaiDV,MUCPHI.DonGia,DONGXE.HangXe,DANGKYCUNGCAP.NgayBatDauCungCap,DANGKYCUNGCAP.NgayKetThucCungCap
FROM NHACUNGCAP 
	LEFT JOIN DANGKYCUNGCAP ON NHACUNGCAP.MaNhaCC=DANGKYCUNGCAP.MaNhaCC 
    LEFT JOIN LOAIDICHVU ON DANGKYCUNGCAP.MaLoaiDv=LOAIDICHVU.MaLoaiDV
    LEFT JOIN MUCPHI ON DANGKYCUNGCAP.MaMP=MUCPHI.MaMP
    LEFT JOIN DONGXE ON DANGKYCUNGCAP.Dongxe=DONGXE.Dongxe;

-- cau 9
SELECT *
FROM NHACUNGCAP 
JOIN DANGKYCUNGCAP 
JOIN DONGXE  ON NHACUNGCAP.MaNhaCC = DANGKYCUNGCAP.MaNhaCC AND DANGKYCUNGCAP.Dongxe = DONGXE.Dongxe
WHERE DONGXE.HangXe='Hiace' OR DONGXE.HangXe='Cerato';

-- cau10
SELECT *
FROM NHACUNGCAP 
WHERE MaNhaCC NOT IN( SELECT MaNhaCC FROM DANGKYCUNGCAP);






